// Date: 5/2/2014 12:17:19 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mythology.model.armor;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCelestialBronzeArmor extends ModelBiped
{
  //fields
    ModelRenderer lift_fin;
    ModelRenderer right_fin;
    ModelRenderer back_fin;
    ModelRenderer neck_fin;
    ModelRenderer hean_fin;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
  
  public ModelCelestialBronzeArmor(float f)
  {
	super(f, 0, 64,64);
    textureWidth = 64;
    textureHeight = 32;
    
      lift_fin = new ModelRenderer(this, 32, 0);
      lift_fin.addBox(0F, 7F, 2F, 0, 5, 2);
      lift_fin.setRotationPoint(2F, 12F, 0F);
      lift_fin.setTextureSize(64, 32);
      lift_fin.mirror = true;
      setRotation(lift_fin, 0F, 0F, 0F);
      right_fin = new ModelRenderer(this, 32, 0);
      right_fin.addBox(0F, 7F, 2F, 0, 5, 2);
      right_fin.setRotationPoint(-2F, 12F, 0F);
      right_fin.setTextureSize(64, 32);
      right_fin.mirror = true;
      setRotation(right_fin, 0F, 0F, 0F);
      back_fin = new ModelRenderer(this, 36, 0);
      back_fin.addBox(0F, 0F, 2F, 0, 14, 2);
      back_fin.setRotationPoint(0F, 0F, 0F);
      back_fin.setTextureSize(64, 32);
      back_fin.mirror = true;
      setRotation(back_fin, 0F, 0F, 0F);
      neck_fin = new ModelRenderer(this, 40, 0);
      neck_fin.addBox(0F, -8F, 4F, 0, 10, 2);
      neck_fin.setRotationPoint(0F, 0F, 0F);
      neck_fin.setTextureSize(64, 32);
      neck_fin.mirror = true;
      setRotation(neck_fin, 0F, 0F, 0F);
      hean_fin = new ModelRenderer(this, 44, 0);
      hean_fin.addBox(0F, -10F, -4F, 0, 2, 10);
      hean_fin.setRotationPoint(0F, 0F, 0F);
      hean_fin.setTextureSize(64, 32);
      hean_fin.mirror = true;
      setRotation(hean_fin, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      
      this.bipedBody.addChild(body);
      this.bipedHead.addChild(head);
      this.bipedLeftArm.addChild(leftarm);
      this.bipedRightArm.addChild(rightarm);
      this.bipedLeftLeg.addChild(leftleg);
     this.bipedRightLeg.addChild(rightleg);
     this.bipedHeadwear.addChild(neck_fin);
     this.bipedLeftArm.addChild(lift_fin);
     this.bipedRightArm.addChild(right_fin);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    lift_fin.render(f5);
    right_fin.render(f5);
    back_fin.render(f5);
    neck_fin.render(f5);
    hean_fin.render(f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
